import { BakeCategory, BakeProduct, BoxSelection, FilterPill, FilterSection, InfoCard, OptionGroup } from '@/types';

export const BAKES_HERO = {
    title: 'Freshly Baked Goodies',
    subtitle: 'Brownies, cookies, cupcakes and more baked fresh for every occasion.',
    primaryCta: 'Order Now',
    secondaryCta: 'Customize Your Box',
    image: '/images/daily-bakes.png',
};

export const BAKE_CATEGORIES: BakeCategory[] = [
    {
        id: 'brownies',
        title: 'Brownies',
        description: 'Dense, glossy, and indulgent squares made for gifting, sharing, and late-night cravings.',
        items: [
            {
                id: 'brownie-1',
                name: 'Chocolate Brownies',
                category: 'Brownies',
                price: 14,
                priceLabel: 'from PKR 14',
                image: '/images/salted-caramel.png',
                imageAlt: 'Chocolate brownie stack with rich glaze',
                description: 'Rich chocolate brownies with soft centers and crisp edges.',
                tags: ['Best Seller'],
            },
            {
                id: 'brownie-2',
                name: 'Fudge Brownies',
                category: 'Brownies',
                price: 16,
                priceLabel: 'from PKR 16',
                image: '/images/velvet-rose.png',
                imageAlt: 'Fudge brownies styled on a dessert plate',
                description: 'Extra fudgy bites layered with deep cocoa flavor.',
            },
            {
                id: 'brownie-3',
                name: 'Nutella Brownies',
                category: 'Brownies',
                price: 18,
                priceLabel: 'from PKR 18',
                image: '/images/signature-cake.png',
                imageAlt: 'Nutella brownies for gifting',
                description: 'Nutella swirls folded into a dark, chewy brownie base.',
            },
            {
                id: 'brownie-4',
                name: 'Lotus Brownies',
                category: 'Brownies',
                price: 18,
                priceLabel: 'from PKR 18',
                image: '/images/celestial.png',
                imageAlt: 'Lotus brownies with caramel notes',
                description: 'Caramel biscuit flavor finished with Lotus crumb on top.',
            },
            {
                id: 'brownie-5',
                name: 'Oreo Brownies',
                category: 'Brownies',
                price: 17,
                priceLabel: 'from PKR 17',
                image: '/images/birthday-cake.png',
                imageAlt: 'Oreo brownie squares with creamy topping',
                description: 'Chunky Oreo pieces baked into a rich chocolate center.',
            },
            {
                id: 'brownie-6',
                name: 'Custom Brownie Box',
                category: 'Brownies',
                price: 24,
                priceLabel: 'from PKR 24',
                image: '/images/journey-4.png',
                imageAlt: 'Assorted brownie box for gifting',
                description: 'Mix your favorite flavors into one premium brownie box.',
            },
        ],
    },
    {
        id: 'cookies',
        title: 'Cookies',
        description: 'Comforting classics and stuffed signatures available in easy-to-order gift boxes.',
        items: [
            {
                id: 'cookie-1',
                name: 'Chocolate Chip Cookies',
                category: 'Cookies',
                price: 12,
                priceLabel: 'Box of 6 from PKR 12',
                image: '/images/daily-bakes.png',
                imageAlt: 'Chocolate chip cookies arranged on a tray',
                description: 'Soft, buttery cookies filled with melty chocolate chips.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
            {
                id: 'cookie-2',
                name: 'Double Chocolate Cookies',
                category: 'Cookies',
                price: 13,
                priceLabel: 'Box of 6 from PKR 13',
                image: '/images/salted-caramel.png',
                imageAlt: 'Double chocolate cookies with glossy finish',
                description: 'Deep cocoa cookies loaded with dark chocolate chunks.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
            {
                id: 'cookie-3',
                name: 'Peanut Butter Cookies',
                category: 'Cookies',
                price: 13,
                priceLabel: 'Box of 6 from PKR 13',
                image: '/images/journey-3.png',
                imageAlt: 'Peanut butter cookies for box orders',
                description: 'Warm peanut butter cookies with a soft and crumbly bite.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
            {
                id: 'cookie-4',
                name: 'Nutella Filled Cookies',
                category: 'Cookies',
                price: 15,
                priceLabel: 'Box of 6 from PKR 15',
                image: '/images/hero-cake.png',
                imageAlt: 'Nutella-filled cookies styled for bakery menu',
                description: 'Thick cookies hiding a molten Nutella center.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
            {
                id: 'cookie-5',
                name: 'Oatmeal Cookies',
                category: 'Cookies',
                price: 12,
                priceLabel: 'Box of 6 from PKR 12',
                image: '/images/journey-2.png',
                imageAlt: 'Oatmeal cookies arranged on table',
                description: 'Golden oatmeal cookies with a toasty, homestyle finish.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
            {
                id: 'cookie-6',
                name: 'Custom Cookie Box',
                category: 'Cookies',
                price: 22,
                priceLabel: 'from PKR 22',
                image: '/images/velvet-rose.png',
                imageAlt: 'Custom cookie box for celebration gifting',
                description: 'Build a crowd-pleasing cookie box in your favorite flavors.',
                boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
            },
        ],
    },
    {
        id: 'cupcakes',
        title: 'Cupcakes',
        description: 'Perfect for dessert tables, gifting, and little moments that still deserve something special.',
        items: [
            {
                id: 'cupcake-1',
                name: 'Chocolate Cupcakes',
                category: 'Cupcakes',
                price: 16,
                priceLabel: 'Box of 4 from PKR 16',
                image: '/images/celestial.png',
                imageAlt: 'Chocolate cupcakes with creamy swirl',
                description: 'Moist chocolate sponge finished with silky chocolate frosting.',
                boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
            },
            {
                id: 'cupcake-2',
                name: 'Vanilla Cupcakes',
                category: 'Cupcakes',
                price: 15,
                priceLabel: 'Box of 4 from PKR 15',
                image: '/images/velvet-rose.png',
                imageAlt: 'Vanilla cupcakes with elegant cream topping',
                description: 'Classic vanilla cupcakes with smooth whipped frosting.',
                boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
            },
            {
                id: 'cupcake-3',
                name: 'Red Velvet Cupcakes',
                category: 'Cupcakes',
                price: 17,
                priceLabel: 'Box of 4 from PKR 17',
                image: '/images/birthday-cake.png',
                imageAlt: 'Red velvet cupcakes for party trays',
                description: 'Soft red velvet crumb topped with cream cheese frosting.',
                boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
                tags: ['Most Loved'],
            },
            {
                id: 'cupcake-4',
                name: 'Lotus Cupcakes',
                category: 'Cupcakes',
                price: 17,
                priceLabel: 'Box of 4 from PKR 17',
                image: '/images/journey-1.png',
                imageAlt: 'Lotus cupcakes with biscuit glaze',
                description: 'Biscoff sponge crowned with Lotus buttercream and crumb.',
                boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
            },
            {
                id: 'cupcake-5',
                name: 'Custom Cupcakes',
                category: 'Cupcakes',
                price: 20,
                priceLabel: 'from PKR 20',
                image: '/images/signature-cake.png',
                imageAlt: 'Custom cupcake box for events',
                description: 'Choose your flavor, colors, and toppings for celebration boxes.',
                boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
            },
        ],
    },
];

export const CUSTOMIZATION_OPTIONS: OptionGroup[] = [
    {
        id: 'flavor',
        title: 'Flavor',
        options: ['Chocolate', 'Vanilla', 'Red Velvet', 'Nutella', 'Lotus'],
    },
    {
        id: 'quantity',
        title: 'Quantity',
        options: ['Box of 4', 'Box of 6', 'Box of 12', 'Box of 24'],
    },
    {
        id: 'box-type',
        title: 'Box Type',
        options: ['Classic Box', 'Gift Box', 'Party Tray', 'Office Box'],
    },
    {
        id: 'add-ons',
        title: 'Add-ons',
        options: ['Sprinkles', 'Chocolate Drizzle', 'Name Writing', 'Toppers', 'Gift Wrapping', 'Message Card'],
    },
];

export const BUILD_YOUR_BOX: BoxSelection[] = [
    {
        id: 'box-1',
        quantity: '2',
        item: 'Brownies',
        note: 'Choose rich classics or signature filled flavors.',
    },
    {
        id: 'box-2',
        quantity: '4',
        item: 'Cookies',
        note: 'Mix soft-baked favorites for a more generous box.',
    },
    {
        id: 'box-3',
        quantity: '2',
        item: 'Cupcakes',
        note: 'Finish with a pair of celebration-ready cupcakes.',
    },
];

export const SPECIAL_OCCASIONS: InfoCard[] = [
    {
        id: 'occasion-1',
        title: 'Birthday Box',
        description: 'Playful colors, candles, toppers, and a ready-to-gift bakery box.',
    },
    {
        id: 'occasion-2',
        title: 'Anniversary Box',
        description: 'Elegant flavors and styling made for intimate celebrations.',
    },
    {
        id: 'occasion-3',
        title: 'Gift Box',
        description: 'Wrapped and finished with a message card for thoughtful gifting.',
    },
    {
        id: 'occasion-4',
        title: 'Office Treat Box',
        description: 'Easy shareable selections sized for meetings, launches, and team wins.',
    },
];

export const POPULAR_BAKES: BakeProduct[] = [
    {
        id: 'popular-1',
        name: 'Lotus Brownies',
        category: 'Most Loved',
        price: 18,
        priceLabel: 'from PKR 18',
        image: '/images/celestial.png',
        description: 'Caramel biscuit richness with a soft, gooey center.',
    },
    {
        id: 'popular-2',
        name: 'Red Velvet Cupcakes',
        category: 'Most Loved',
        price: 17,
        priceLabel: 'Box of 4 from PKR 17',
        image: '/images/birthday-cake.png',
        description: 'Cream cheese frosting and soft velvet crumb in every bite.',
    },
    {
        id: 'popular-3',
        name: 'Chocolate Chip Cookies',
        category: 'Best Seller',
        price: 12,
        priceLabel: 'Box of 6 from PKR 12',
        image: '/images/daily-bakes.png',
        description: 'A bakery staple with golden edges and soft centers.',
    },
    {
        id: 'popular-4',
        name: 'Fudge Brownies',
        category: 'Best Seller',
        price: 16,
        priceLabel: 'from PKR 16',
        image: '/images/velvet-rose.png',
        description: 'Deep cocoa intensity for serious brownie lovers.',
    },
];

export const DELIVERY_HIGHLIGHTS: InfoCard[] = [
    {
        id: 'delivery-1',
        title: 'Same Day Delivery',
        description: 'Available on selected menu items for last-minute gifting and cravings.',
    },
    {
        id: 'delivery-2',
        title: 'Freshly Baked Daily',
        description: 'Small-batch preparation keeps each order feeling fresh and premium.',
    },
    {
        id: 'delivery-3',
        title: 'Custom Orders Available',
        description: 'Personalized flavor mixes, color themes, and event-ready packaging.',
    },
    {
        id: 'delivery-4',
        title: 'Delivery Across City',
        description: 'We deliver your bakery box securely across the city with care.',
    },
];

export const BAKES_FILTER_PILLS: FilterPill[] = [
    { id: 'all', label: 'All', active: true },
    { id: 'brownies', label: 'Brownies' },
    { id: 'cookies', label: 'Cookies' },
    { id: 'cupcakes', label: 'Cupcakes' },
    { id: 'gift-boxes', label: 'Gift Boxes' },
    { id: 'custom', label: 'Custom Box' },
];

export const BAKES_SORT_OPTIONS = ['Popularity', 'Newest', 'Price Low to High'];

export const BAKES_SIDEBAR_FILTERS: FilterSection[] = [
    {
        id: 'size',
        title: 'Box Size',
        style: 'radio',
        options: ['Box of 4', 'Box of 6', 'Box of 12', 'Box of 24'],
    },
    {
        id: 'occasion',
        title: 'Occasion',
        style: 'pill',
        options: ['Birthday', 'Wedding', 'Anniversary', 'Graduation'],
    },
];

export const BAKES_SHOP_ITEMS: BakeProduct[] = [
    {
        id: 'shop-1',
        name: 'Lotus Brownies',
        category: 'Brownies',
        price: 18,
        priceLabel: 'PKR 18',
        image: '/images/celestial.png',
        description: 'Caramel biscuit richness layered into a glossy, chewy brownie square.',
        boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
        occasions: ['Birthday', 'Anniversary'],
    },
    {
        id: 'shop-2',
        name: 'Chocolate Chip Cookies',
        category: 'Cookies',
        price: 12,
        priceLabel: 'PKR 12',
        image: '/images/daily-bakes.png',
        description: 'Golden-edged cookies with a soft center and generous chocolate melt.',
        boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
        occasions: ['Birthday', 'Graduation'],
    },
    {
        id: 'shop-3',
        name: 'Red Velvet Cupcakes',
        category: 'Cupcakes',
        price: 17,
        priceLabel: 'PKR 17',
        image: '/images/birthday-cake.png',
        description: 'Soft velvet crumb topped with cream cheese frosting for party tables.',
        boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
        occasions: ['Birthday', 'Wedding'],
    },
    {
        id: 'shop-4',
        name: 'Fudge Brownies',
        category: 'Brownies',
        price: 16,
        priceLabel: 'PKR 16',
        image: '/images/velvet-rose.png',
        description: 'Dense cocoa depth with the kind of center brownie lovers look for.',
        boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
        occasions: ['Anniversary', 'Graduation'],
    },
    {
        id: 'shop-5',
        name: 'Nutella Filled Cookies',
        category: 'Cookies',
        price: 15,
        priceLabel: 'PKR 15',
        image: '/images/hero-cake.png',
        description: 'Thick bakery cookies with a molten Nutella center in every bite.',
        boxOptions: ['Box of 6', 'Box of 12', 'Box of 24'],
        occasions: ['Wedding', 'Graduation'],
    },
    {
        id: 'shop-6',
        name: 'Custom Cupcake Box',
        category: 'Cupcakes',
        price: 20,
        priceLabel: 'PKR 20',
        image: '/images/signature-cake.png',
        description: 'Choose your sponge, palette, and toppings for a celebration-ready box.',
        boxOptions: ['Box of 4', 'Box of 6', 'Box of 12'],
        occasions: ['Birthday', 'Wedding', 'Anniversary'],
        tags: ['Custom Box'],
    },
    {
        id: 'shop-7',
        name: 'Gift Brownie Box',
        category: 'Brownies',
        price: 24,
        priceLabel: 'PKR 24',
        image: '/images/journey-4.png',
        description: 'Assorted premium brownies packed for gifting with a message card.',
        boxOptions: ['Box of 6', 'Box of 12'],
        occasions: ['Birthday', 'Anniversary', 'Graduation'],
        tags: ['Gift Boxes'],
    },
    {
        id: 'shop-8',
        name: 'Celebration Cookie Box',
        category: 'Cookies',
        price: 22,
        priceLabel: 'PKR 22',
        image: '/images/journey-3.png',
        description: 'Mixed cookie box curated for party tables and office gifting.',
        boxOptions: ['Box of 12', 'Box of 24'],
        occasions: ['Birthday', 'Wedding', 'Graduation'],
        tags: ['Gift Boxes'],
    },
];
