import { CakeProduct, FilterPill, FilterSection } from '@/types';

export const CAKE_HERO = {
    title: 'Perfectly Crafted Cakes',
    subtitle: 'Classic, custom, tiered cakes and more crafted fresh for every occasion.',
    image1: '/cake.png',
    image2: '/chocolate-cake.png',
};

export const CAKE_SORT_OPTIONS = ['Popularity', 'Newest', 'Price Low to High'];

export const CAKE_FILTER_PILLS: FilterPill[] = [
    { id: 'all', label: 'All', active: true },
    { id: 'chocolate', label: 'Chocolate' },
    { id: 'red-velvet', label: 'Red Velvet' },
    { id: 'vanilla', label: 'Vanilla' },
    { id: 'photo-cake', label: 'Photo Cake' },
    { id: 'wedding-cake', label: 'Wedding Cake' },
];

export const CAKE_SIDEBAR_FILTERS: FilterSection[] = [
    {
        id: 'size',
        title: 'Cake Size',
        style: 'radio',
        options: ['4" Bento Cake', '6" Standard', '8" Celebration', 'Tiered Artistry'],
    },
    {
        id: 'occasion',
        title: 'Occasion',
        style: 'pill',
        options: ['Birthday', 'Wedding', 'Anniversary', 'Graduation'],
    },
];

export const CAKE_SHOP_ITEMS: CakeProduct[] = [
    {
        id: 'royal-velvet',
        name: 'Royal Velvet',
        price: 6400,
        image: '/cake.png',
        description: 'Deep cocoa infused with crimson elegance and silky smooth cream cheese.',
        category: 'red-velvet',
        sizeOptions: ['6" Standard', '8" Celebration'],
        occasions: ['Birthday', 'Anniversary'],
        tags: ['Most Loved'],
        dimensions: 'Standard Tier (Serves 12-15)',
        priceLabel: 'PKR 6,400',
    },
    {
        id: 'citrus-bloom',
        name: 'Citrus Bloom',
        price: 4800,
        image: '/pastery.png',
        description: 'Zesty lemon sponge layered with citrus curd and whipped mascarpone.',
        category: 'vanilla',
        sizeOptions: ['4" Bento Cake', '6" Standard'],
        occasions: ['Birthday', 'Graduation'],
        dimensions: 'Standard Tier (Serves 8-10)',
        priceLabel: 'PKR 4,800',
    },
    {
        id: 'midnight-ganache',
        name: 'Midnight Ganache',
        price: 7200,
        image: '/chocolate-cake.png',
        description: 'Rich chocolate infusion with 70% dark Belgian ganache and sea salt flakes.',
        category: 'chocolate',
        sizeOptions: ['6" Standard', '8" Celebration'],
        occasions: ['Wedding', 'Anniversary'],
        tags: ['Best Seller'],
        dimensions: 'Double Tier (Serves 25-30)',
        priceLabel: 'PKR 7,200',
    },
    {
        id: 'summer-berry',
        name: 'Summer Berry',
        price: 5500,
        image: '/cake.png',
        description: 'Light vanilla sponge with locally sourced berries and chantilly cream.',
        category: 'vanilla',
        sizeOptions: ['4" Bento Cake', '6" Standard'],
        occasions: ['Birthday', 'Graduation'],
        dimensions: 'Standard Tier (Serves 12-15)',
        priceLabel: 'PKR 5,500',
    },
    {
        id: 'ivory-orchid',
        name: 'Ivory Orchid',
        price: 24000,
        image: '/cake.png',
        description: 'A two-tiered architectural masterpiece with almond and honey notes.',
        category: 'wedding-cake',
        sizeOptions: ['Tiered Artistry'],
        occasions: ['Wedding', 'Anniversary'],
        tags: ['Best Seller', 'Most Loved'],
        dimensions: 'Three Tier (Serves 45-50)',
        priceLabel: 'PKR 24,000',
    },
    {
        id: 'caramel-drift',
        name: 'Caramel Drift',
        price: 5800,
        image: '/pastery.png',
        description: 'Dense coffee cake with burnt caramel glaze and sea salt crunch.',
        category: 'chocolate',
        sizeOptions: ['6" Standard', '8" Celebration'],
        occasions: ['Anniversary', 'Graduation'],
        dimensions: 'Standard Tier (Serves 12-15)',
        priceLabel: 'PKR 5,800',
    },
    {
        id: 'pixel-party',
        name: 'Pixel Party',
        price: 8400,
        image: '/chocolate-cake.png',
        description: 'Custom edible photo print cake with buttercream frame and confetti texture.',
        category: 'photo-cake',
        sizeOptions: ['6" Standard', '8" Celebration'],
        occasions: ['Birthday', 'Graduation'],
        tags: ['Custom'],
        dimensions: 'Double Tier (Serves 20-25)',
        priceLabel: 'PKR 8,400',
    },
    {
        id: 'gold-ribbon',
        name: 'Gold Ribbon',
        price: 13200,
        image: '/cake.png',
        description: 'Floral fondant styling with smooth vanilla sponge for elegant gatherings.',
        category: 'wedding-cake',
        sizeOptions: ['8" Celebration', 'Tiered Artistry'],
        occasions: ['Wedding', 'Anniversary'],
        dimensions: 'Two Tier (Serves 30-35)',
        priceLabel: 'PKR 13,200',
    },
    {
        id: 'crimson-frost',
        name: 'Crimson Frost',
        price: 6800,
        image: '/chocolate-cake.png',
        description: 'Classic red velvet layers with whipped cream cheese and berry glaze.',
        category: 'red-velvet',
        sizeOptions: ['6" Standard', '8" Celebration'],
        occasions: ['Birthday', 'Wedding'],
        dimensions: 'Standard Tier (Serves 12-15)',
        priceLabel: 'PKR 6,800',
    },
];
